name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    environment : production
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DB_URL : ${{ vars.DB_URL }}

    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull $DOCKER_USERNAME/onlyclick-server:latest

      - name: Delete old container if it exists
        run: |
          if [ "$(sudo docker ps -aq -f name=onlyclick-server-container)" ]; then
            echo "Old container found. Removing..."
            sudo docker rm -f onlyclick-server-container
          else
            echo "No existing container to remove."
          fi

      - name: Run new container
        run: |
          sudo docker run -d \
            --env-file .env \
            -p 8000:8000 \
            -e PORT=8000 \
            --name onlyclick-server-container \
            $DOCKER_USERNAME/onlyclick-server:latest