name: ci

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: | 
            echo $DOCKER_USERNAME
            echo $DOCKER_PASSWORD
            docker login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_USERNAME"/onlyclick-server"

      - name: Push Image to Docker Hub
        run: docker push $DOCKER_USERNAME"/onlyclick-server"